### ISSUE TITLE
Get MRZ info from picture of a passport (not a nice scan of a passport)

### ISSUE THREAD

**Issue by tonyhardcode** [sivakumar-mahalingam/passport-mrz-reader#9]
I tried taking not perfect photos of a passport held by my hand (but the MRZ is very legible) in the photo. Sending these to fastmrz gives me:

Array
(
    [text] => JSON:
{
    "status": "FAILURE",
    "message": "No MRZ detected"
}

TEXT:

)

Is it possible to just have the python script look for just the MRZ in a photo and ignoring the rest of the image?

**Comment by sivakumar-mahalingam** [comment]
Let me try to replicate and keep you posted.

**Comment by sivakumar-mahalingam** [comment]
Fixed in the version 2.0.2

**Comment by tonyhardcode** [comment]
Upgraded to version 2.0.2 but still having issues with photos taken of passports being held by my hand.

**Comment by sivakumar-mahalingam** [comment]
I have done using a passport image and it was working. I will try with a low resolution image of the same

**Comment by cookienommienom** [comment]
Currently having this issue as well with a USA passport. The image is pretty clear as well. Let me know what I can do to help troubleshoot this
